apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-web-app-test
  template:
    metadata:
      labels:
        app: node-web-app-test
    spec:
      containers:
      - name: node-web-app-test
        image: node-web-app-test:local
        imagePullPolicy: Never
      restartPolicy: Always